# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaAhorros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=5)),
                ('logo', models.FilePathField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(default='direccion', max_length=10)),
                ('sexo', models.CharField(choices=[('f', 'femenino'), ('m', 'masculino')], max_length=10)),
                ('estadoCivil', models.CharField(choices=[('soltero', 'soltero'), ('casado', 'casado'), ('divorciado', 'divorciado'), ('viudo', 'viudo')], max_length=10)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('idCA', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='caja.CajaAhorros')),
            ],
        ),
    ]
