# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cuentaahorros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(default='dexcripcion', max_length=50)),
                ('tipo', models.CharField(choices=[('d', 'deposito'), ('r', 'retiro')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('idCuenta', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='caja.CuentaAhorros')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(default='direccion', max_length=100),
        ),
    ]
